spring:
  servlet:
    multipart:
      max-file-size: 10MB # 최대 용량 설정
      max-request-size: 10MB # 최대 용량 설정

  datasource:
    url: jdbc:mysql://localhost:3306/travelland
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  mail:
    host: smtp.gmail.com
    port: 587
    username: puffern12@gmail.com
    password: dqwoxshmxlgrseeq

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000

    data:
      redis:
        port: 6379
        host: localhost

  elasticsearch:
    username: elastic
    password: admin123
    uris: 34.64.57.218:9200

  # JWT secret key
jwt:
  secret:
    key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==

app:
  security:
    ceoToken: "AAABnvxRVklrnYxKZ0aHgTBcXukeZygoC"

# AWS S3
cloud:
  aws:
    s3:
      bucket: dev-travelland
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      access-key: AKIAVRUVRYWZHNJO6YNS
      secret-key: 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

#https
server:
  port: 443
  port.http: 80
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: admin123
    key-store-type: PKCS12

# Swagger 설정
springdoc:
  show-login-endpoint: true # 시큐리티 로그인 endpoint 사용
  use-fqn: true # 클래스 경로 관리시 패키지 경로를 포함해서 관리

